"""
Module to convert text in speech
"""
from gtts import gTTS
from tempfile import NamedTemporaryFile
from playsound import playsound


def tts(lang, txt):
    """
    Convert text to speech.

    It uses the gTTS package under the hood.

    Parameters
    ----------
    lang : str
        Language of the model.
        example: 'en', 'pt', 'es', 'fr', 'de', 'ro', 'ca', 'it'

    text : str
        Text to be convert

    Returns
    -------
    Stream of the sound generated by the converter.

    See Also
    --------
    linguae.forvo : Open browser and query audio samples from Forvo site.

    Examples
    --------
    >>> linguae.tts('en','I like to study languages.')
    >>> linguae.tts('pt','Gosto de estudar idiomas.')
    """
    gTTS(text=txt, lang=lang).write_to_fp(voice := NamedTemporaryFile())
    playsound(voice.name)
    voice.close()
